app:
  telegram-token: ${TELEGRAM_TOKEN} # env variable

spring:
  application:
    name: Bot
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8082

scrapper:
  url: scrapper
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
